/**
 * Dummy DS Articles for POC/Preview purposes
 * Retail Store Products - Grocery, Fresh, Household, etc.
 * Frontend can use this data for layout binding in DS preview
 */
const DUMMY_DS_ARTICLES = [
  {
    "ean": "6410901122000",
    "displaytype": "3",
    "promotion": "1",
    "promotion_start_dt": "2026-09-01",
    "promotion_end_dt": "2026-09-15",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122000",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122000.jpg",
    "sok_id": "111283993000",
    "name_l1": "Kuoma lasten välikausikenkä Musta, 28",
    "name_l2": "Kuoma barnskor Musta, 28",
    "name_func_l1": "Model 1",
    "name_func_l2": "Modell 1",
    "name25_l1": "Lasten kenkä Musta",
    "name25_l2": "Barnsko Musta",
    "name40_l1": "Kuoma välikausikenkä Musta, 28",
    "name40_l2": "Kuoma barnskor Musta, 28",
    "guarantee_l1": "6 kk",
    "guarantee_l2": "11 mån",
    "brand_l1": "Kuoma",
    "brand_l2": "Kuoma",
    "group": "G0",
    "presentation_group": "GBAACK",
    "price_normal": 53.5,
    "price_normal_int": "53",
    "price_normal_frac": "50",
    "price_normal_per_unit": 53.5,
    "price_normal_per_unit_int": "53",
    "price_normal_per_unit_frac": "50",
    "price_current": 49.75,
    "price_current_int": "49",
    "price_current_frac": "75",
    "price_current_per_unit": 49.75,
    "price_current_per_unit_int": "49",
    "price_current_per_unit_frac": "75",
    "price_30day_lowest": 44.75,
    "price_deposit": "0.5",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "7",
    "price_unit_l1": "KPL",
    "price_unit_l2": "PR",
    "package_unit_size": 2,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 1",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 1",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Musta.",
    "marketing_text_l2": "Högkvalitativa barnskor Musta.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Suomi",
    "origin_country_l2": "Suomi",
    "attr_gluten_free": "",
    "attr_vegan": "1",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "A",
    "age_limit": "3+",
    "variable_weight_product": "0",
    "scale_number": "8",
    "blue_swan": "1",
    "top_brand": "Kuoma",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-01",
    "assortment_end": "2027-03-01",
    "assortment_status": "3",
    "product_group": "H",
    "aims_price_normal": 53.5,
    "aims_price_sale": 49.75,
    "aims_discount_pct": 7
  },
  {
    "ean": "6410901122001",
    "displaytype": "2",
    "promotion": "1",
    "promotion_start_dt": "2026-09-02",
    "promotion_end_dt": "2026-09-16",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122001",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122001.jpg",
    "sok_id": "111283993001",
    "name_l1": "Viking lasten välikausikenkä Sininen, 29",
    "name_l2": "Viking barnskor Sininen, 29",
    "name_func_l1": "Model 2",
    "name_func_l2": "Modell 2",
    "name25_l1": "Lasten kenkä Sininen",
    "name25_l2": "Barnsko Sininen",
    "name40_l1": "Viking välikausikenkä Sininen, 29",
    "name40_l2": "Viking barnskor Sininen, 29",
    "guarantee_l1": "13 kk",
    "guarantee_l2": "13 mån",
    "brand_l1": "Viking",
    "brand_l2": "Viking",
    "group": "G1",
    "presentation_group": "GBASHO",
    "price_normal": 58.2,
    "price_normal_int": "58",
    "price_normal_frac": "20",
    "price_normal_per_unit": 58.2,
    "price_normal_per_unit_int": "58",
    "price_normal_per_unit_frac": "20",
    "price_current": 47.14,
    "price_current_int": "47",
    "price_current_frac": "14",
    "price_current_per_unit": 47.14,
    "price_current_per_unit_int": "47",
    "price_current_per_unit_frac": "14",
    "price_30day_lowest": 46.11,
    "price_deposit": "0",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "19",
    "price_unit_l1": "PARI",
    "price_unit_l2": "PR",
    "package_unit_size": 1,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 2",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 2",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Sininen.",
    "marketing_text_l2": "Högkvalitativa barnskor Sininen.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Finland",
    "origin_country_l2": "Finland",
    "attr_gluten_free": "",
    "attr_vegan": "1",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "1",
    "attr_alcohol_pct": "0",
    "attr_local": "1",
    "attr_quality_class": "A",
    "age_limit": "3+",
    "variable_weight_product": "0",
    "scale_number": "4",
    "blue_swan": "0",
    "top_brand": "Viking",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-02",
    "assortment_end": "2027-03-02",
    "assortment_status": "2",
    "product_group": "K",
    "aims_price_normal": 58.2,
    "aims_price_sale": 47.14,
    "aims_discount_pct": 19
  },
  {
    "ean": "6410901122002",
    "displaytype": "1",
    "promotion": "1",
    "promotion_start_dt": "2026-09-03",
    "promotion_end_dt": "2026-09-17",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122002",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122002.jpg",
    "sok_id": "111283993002",
    "name_l1": "Reima lasten välikausikenkä Punainen, 30",
    "name_l2": "Reima barnskor Punainen, 30",
    "name_func_l1": "Model 3",
    "name_func_l2": "Modell 3",
    "name25_l1": "Lasten kenkä Punainen",
    "name25_l2": "Barnsko Punainen",
    "name40_l1": "Reima välikausikenkä Punainen, 30",
    "name40_l2": "Reima barnskor Punainen, 30",
    "guarantee_l1": "6 kk",
    "guarantee_l2": "21 mån",
    "brand_l1": "Reima",
    "brand_l2": "Reima",
    "group": "G2",
    "presentation_group": "GBKIDS",
    "price_normal": 93.54,
    "price_normal_int": "93",
    "price_normal_frac": "54",
    "price_normal_per_unit": 93.54,
    "price_normal_per_unit_int": "93",
    "price_normal_per_unit_frac": "54",
    "price_current": 89.8,
    "price_current_int": "89",
    "price_current_frac": "80",
    "price_current_per_unit": 89.8,
    "price_current_per_unit_int": "89",
    "price_current_per_unit_frac": "80",
    "price_30day_lowest": 86.56,
    "price_deposit": "0",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "4",
    "price_unit_l1": "PARI",
    "price_unit_l2": "PR",
    "package_unit_size": 1,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 3",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 3",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Punainen.",
    "marketing_text_l2": "Högkvalitativa barnskor Punainen.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Sweden",
    "origin_country_l2": "Sweden",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "1",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "A",
    "age_limit": "3+",
    "variable_weight_product": "1",
    "scale_number": "1",
    "blue_swan": "0",
    "top_brand": "Reima",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-03",
    "assortment_end": "2027-03-03",
    "assortment_status": "3",
    "product_group": "G",
    "aims_price_normal": 93.54,
    "aims_price_sale": 89.8,
    "aims_discount_pct": 4
  },
  {
    "ean": "6410901122003",
    "displaytype": "2",
    "promotion": "1",
    "promotion_start_dt": "2026-09-04",
    "promotion_end_dt": "2026-09-18",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122003",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122003.jpg",
    "sok_id": "111283993003",
    "name_l1": "Superfit lasten välikausikenkä Vihreä, 31",
    "name_l2": "Superfit barnskor Vihreä, 31",
    "name_func_l1": "Model 4",
    "name_func_l2": "Modell 4",
    "name25_l1": "Lasten kenkä Vihreä",
    "name25_l2": "Barnsko Vihreä",
    "name40_l1": "Superfit välikausikenkä Vihreä, 31",
    "name40_l2": "Superfit barnskor Vihreä, 31",
    "guarantee_l1": "24 kk",
    "guarantee_l2": "18 mån",
    "brand_l1": "Superfit",
    "brand_l2": "Superfit",
    "group": "G0",
    "presentation_group": "GBSPORT",
    "price_normal": 54.86,
    "price_normal_int": "54",
    "price_normal_frac": "86",
    "price_normal_per_unit": 54.86,
    "price_normal_per_unit_int": "54",
    "price_normal_per_unit_frac": "86",
    "price_current": 44.44,
    "price_current_int": "44",
    "price_current_frac": "44",
    "price_current_per_unit": 44.44,
    "price_current_per_unit_int": "44",
    "price_current_per_unit_frac": "44",
    "price_30day_lowest": 40.94,
    "price_deposit": "0",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "19",
    "price_unit_l1": "PARI",
    "price_unit_l2": "PR",
    "package_unit_size": 2,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 4",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 4",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Vihreä.",
    "marketing_text_l2": "Högkvalitativa barnskor Vihreä.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Germany",
    "origin_country_l2": "Germany",
    "attr_gluten_free": "",
    "attr_vegan": "1",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "1",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "B",
    "age_limit": "3+",
    "variable_weight_product": "0",
    "scale_number": "1",
    "blue_swan": "0",
    "top_brand": "Superfit",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-04",
    "assortment_end": "2027-03-04",
    "assortment_status": "3",
    "product_group": "G",
    "aims_price_normal": 54.86,
    "aims_price_sale": 44.44,
    "aims_discount_pct": 19
  },
  {
    "ean": "6410901122004",
    "displaytype": "3",
    "promotion": "1",
    "promotion_start_dt": "2026-09-05",
    "promotion_end_dt": "2026-09-19",
    "special_promotion": "0",
    "nfc": "https://ewq.zone/product/6410901122004",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122004.jpg",
    "sok_id": "111283993004",
    "name_l1": "ECCO lasten välikausikenkä Keltainen, 32",
    "name_l2": "ECCO barnskor Keltainen, 32",
    "name_func_l1": "Model 5",
    "name_func_l2": "Modell 5",
    "name25_l1": "Lasten kenkä Keltainen",
    "name25_l2": "Barnsko Keltainen",
    "name40_l1": "ECCO välikausikenkä Keltainen, 32",
    "name40_l2": "ECCO barnskor Keltainen, 32",
    "guarantee_l1": "17 kk",
    "guarantee_l2": "13 mån",
    "brand_l1": "ECCO",
    "brand_l2": "ECCO",
    "group": "G1",
    "presentation_group": "GBAACK",
    "price_normal": 96.6,
    "price_normal_int": "96",
    "price_normal_frac": "60",
    "price_normal_per_unit": 96.6,
    "price_normal_per_unit_int": "96",
    "price_normal_per_unit_frac": "60",
    "price_current": 91.77,
    "price_current_int": "91",
    "price_current_frac": "77",
    "price_current_per_unit": 91.77,
    "price_current_per_unit_int": "91",
    "price_current_per_unit_frac": "77",
    "price_30day_lowest": 89.02,
    "price_deposit": "0",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "5",
    "price_unit_l1": "KPL",
    "price_unit_l2": "ST",
    "package_unit_size": 3,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 5",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 5",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Keltainen.",
    "marketing_text_l2": "Högkvalitativa barnskor Keltainen.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Suomi",
    "origin_country_l2": "Suomi",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "Premium",
    "age_limit": "6+",
    "variable_weight_product": "1",
    "scale_number": "10",
    "blue_swan": "0",
    "top_brand": "ECCO",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-05",
    "assortment_end": "2027-03-05",
    "assortment_status": "1",
    "product_group": "H",
    "aims_price_normal": 96.6,
    "aims_price_sale": 91.77,
    "aims_discount_pct": 5
  },
  {
    "ean": "6410901122005",
    "displaytype": "3",
    "promotion": "1",
    "promotion_start_dt": "2026-09-06",
    "promotion_end_dt": "2026-09-20",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122005",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122005.jpg",
    "sok_id": "111283993005",
    "name_l1": "Kuoma lasten välikausikenkä Pinkki, 33",
    "name_l2": "Kuoma barnskor Pinkki, 33",
    "name_func_l1": "Model 6",
    "name_func_l2": "Modell 6",
    "name25_l1": "Lasten kenkä Pinkki",
    "name25_l2": "Barnsko Pinkki",
    "name40_l1": "Kuoma välikausikenkä Pinkki, 33",
    "name40_l2": "Kuoma barnskor Pinkki, 33",
    "guarantee_l1": "21 kk",
    "guarantee_l2": "7 mån",
    "brand_l1": "Kuoma",
    "brand_l2": "Kuoma",
    "group": "G2",
    "presentation_group": "GBASHO",
    "price_normal": 76.28,
    "price_normal_int": "76",
    "price_normal_frac": "28",
    "price_normal_per_unit": 76.28,
    "price_normal_per_unit_int": "76",
    "price_normal_per_unit_frac": "28",
    "price_current": 75.52,
    "price_current_int": "75",
    "price_current_frac": "52",
    "price_current_per_unit": 75.52,
    "price_current_per_unit_int": "75",
    "price_current_per_unit_frac": "52",
    "price_30day_lowest": 74.58,
    "price_deposit": "1",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "1",
    "price_unit_l1": "KPL",
    "price_unit_l2": "PR",
    "package_unit_size": 2,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 6",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 6",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Pinkki.",
    "marketing_text_l2": "Högkvalitativa barnskor Pinkki.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Finland",
    "origin_country_l2": "Finland",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "B",
    "age_limit": "6+",
    "variable_weight_product": "0",
    "scale_number": "2",
    "blue_swan": "0",
    "top_brand": "Kuoma",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-06",
    "assortment_end": "2027-03-06",
    "assortment_status": "2",
    "product_group": "H",
    "aims_price_normal": 76.28,
    "aims_price_sale": 75.52,
    "aims_discount_pct": 1
  },
  {
    "ean": "6410901122006",
    "displaytype": "3",
    "promotion": "0",
    "promotion_start_dt": "",
    "promotion_end_dt": "",
    "special_promotion": "0",
    "nfc": "https://ewq.zone/product/6410901122006",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122006.jpg",
    "sok_id": "111283993006",
    "name_l1": "Viking lasten välikausikenkä Harmaa, 34",
    "name_l2": "Viking barnskor Harmaa, 34",
    "name_func_l1": "Model 7",
    "name_func_l2": "Modell 7",
    "name25_l1": "Lasten kenkä Harmaa",
    "name25_l2": "Barnsko Harmaa",
    "name40_l1": "Viking välikausikenkä Harmaa, 34",
    "name40_l2": "Viking barnskor Harmaa, 34",
    "guarantee_l1": "22 kk",
    "guarantee_l2": "17 mån",
    "brand_l1": "Viking",
    "brand_l2": "Viking",
    "group": "G0",
    "presentation_group": "GBKIDS",
    "price_normal": 77.58,
    "price_normal_int": "77",
    "price_normal_frac": "58",
    "price_normal_per_unit": 77.58,
    "price_normal_per_unit_int": "77",
    "price_normal_per_unit_frac": "58",
    "price_current": 77.58,
    "price_current_int": "77",
    "price_current_frac": "58",
    "price_current_per_unit": 77.58,
    "price_current_per_unit_int": "77",
    "price_current_per_unit_frac": "58",
    "price_30day_lowest": 74.1,
    "price_deposit": "0.5",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "0",
    "price_unit_l1": "KPL",
    "price_unit_l2": "ST",
    "package_unit_size": 2,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 7",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 7",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Harmaa.",
    "marketing_text_l2": "Högkvalitativa barnskor Harmaa.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Sweden",
    "origin_country_l2": "Sweden",
    "attr_gluten_free": "",
    "attr_vegan": "1",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "1",
    "attr_quality_class": "A",
    "age_limit": "",
    "variable_weight_product": "0",
    "scale_number": "6",
    "blue_swan": "0",
    "top_brand": "Viking",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-07",
    "assortment_end": "2027-03-07",
    "assortment_status": "1",
    "product_group": "H",
    "aims_price_normal": 77.58,
    "aims_price_sale": 77.58,
    "aims_discount_pct": 0
  },
  {
    "ean": "6410901122007",
    "displaytype": "2",
    "promotion": "1",
    "promotion_start_dt": "2026-09-08",
    "promotion_end_dt": "2026-09-22",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122007",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122007.jpg",
    "sok_id": "111283993007",
    "name_l1": "Reima lasten välikausikenkä Oranssi, 35",
    "name_l2": "Reima barnskor Oranssi, 35",
    "name_func_l1": "Model 8",
    "name_func_l2": "Modell 8",
    "name25_l1": "Lasten kenkä Oranssi",
    "name25_l2": "Barnsko Oranssi",
    "name40_l1": "Reima välikausikenkä Oranssi, 35",
    "name40_l2": "Reima barnskor Oranssi, 35",
    "guarantee_l1": "17 kk",
    "guarantee_l2": "20 mån",
    "brand_l1": "Reima",
    "brand_l2": "Reima",
    "group": "G1",
    "presentation_group": "GBSPORT",
    "price_normal": 55.93,
    "price_normal_int": "55",
    "price_normal_frac": "93",
    "price_normal_per_unit": 55.93,
    "price_normal_per_unit_int": "55",
    "price_normal_per_unit_frac": "93",
    "price_current": 52.57,
    "price_current_int": "52",
    "price_current_frac": "57",
    "price_current_per_unit": 52.57,
    "price_current_per_unit_int": "52",
    "price_current_per_unit_frac": "57",
    "price_30day_lowest": 50.52,
    "price_deposit": "1",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "6",
    "price_unit_l1": "PARI",
    "price_unit_l2": "ST",
    "package_unit_size": 1,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 8",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 8",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Oranssi.",
    "marketing_text_l2": "Högkvalitativa barnskor Oranssi.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Germany",
    "origin_country_l2": "Germany",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "1",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "Premium",
    "age_limit": "6+",
    "variable_weight_product": "1",
    "scale_number": "8",
    "blue_swan": "1",
    "top_brand": "Reima",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-08",
    "assortment_end": "2027-03-08",
    "assortment_status": "3",
    "product_group": "K",
    "aims_price_normal": 55.93,
    "aims_price_sale": 52.57,
    "aims_discount_pct": 6
  },
  {
    "ean": "6410901122008",
    "displaytype": "3",
    "promotion": "1",
    "promotion_start_dt": "2026-09-09",
    "promotion_end_dt": "2026-09-23",
    "special_promotion": "0",
    "nfc": "https://ewq.zone/product/6410901122008",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122008.jpg",
    "sok_id": "111283993008",
    "name_l1": "Superfit lasten välikausikenkä Violetti, 36",
    "name_l2": "Superfit barnskor Violetti, 36",
    "name_func_l1": "Model 9",
    "name_func_l2": "Modell 9",
    "name25_l1": "Lasten kenkä Violetti",
    "name25_l2": "Barnsko Violetti",
    "name40_l1": "Superfit välikausikenkä Violetti, 36",
    "name40_l2": "Superfit barnskor Violetti, 36",
    "guarantee_l1": "16 kk",
    "guarantee_l2": "20 mån",
    "brand_l1": "Superfit",
    "brand_l2": "Superfit",
    "group": "G2",
    "presentation_group": "GBAACK",
    "price_normal": 76.86,
    "price_normal_int": "76",
    "price_normal_frac": "86",
    "price_normal_per_unit": 76.86,
    "price_normal_per_unit_int": "76",
    "price_normal_per_unit_frac": "86",
    "price_current": 71.48,
    "price_current_int": "71",
    "price_current_frac": "48",
    "price_current_per_unit": 71.48,
    "price_current_per_unit_int": "71",
    "price_current_per_unit_frac": "48",
    "price_30day_lowest": 67.01,
    "price_deposit": "1",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "7",
    "price_unit_l1": "PARI",
    "price_unit_l2": "PR",
    "package_unit_size": 3,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 9",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 9",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Violetti.",
    "marketing_text_l2": "Högkvalitativa barnskor Violetti.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Suomi",
    "origin_country_l2": "Suomi",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "1",
    "attr_quality_class": "Premium",
    "age_limit": "3+",
    "variable_weight_product": "1",
    "scale_number": "9",
    "blue_swan": "1",
    "top_brand": "Superfit",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-09",
    "assortment_end": "2027-03-09",
    "assortment_status": "1",
    "product_group": "G",
    "aims_price_normal": 76.86,
    "aims_price_sale": 71.48,
    "aims_discount_pct": 7
  },
  {
    "ean": "6410901122009",
    "displaytype": "2",
    "promotion": "1",
    "promotion_start_dt": "2026-09-10",
    "promotion_end_dt": "2026-09-24",
    "special_promotion": "1",
    "nfc": "https://ewq.zone/product/6410901122009",
    "img_url": "https://cdn.s-cloud.fi/v1/product/ean/6410901122009.jpg",
    "sok_id": "111283993009",
    "name_l1": "ECCO lasten välikausikenkä Ruskea, 37",
    "name_l2": "ECCO barnskor Ruskea, 37",
    "name_func_l1": "Model 10",
    "name_func_l2": "Modell 10",
    "name25_l1": "Lasten kenkä Ruskea",
    "name25_l2": "Barnsko Ruskea",
    "name40_l1": "ECCO välikausikenkä Ruskea, 37",
    "name40_l2": "ECCO barnskor Ruskea, 37",
    "guarantee_l1": "23 kk",
    "guarantee_l2": "8 mån",
    "brand_l1": "ECCO",
    "brand_l2": "ECCO",
    "group": "G0",
    "presentation_group": "GBASHO",
    "price_normal": 70.26,
    "price_normal_int": "70",
    "price_normal_frac": "26",
    "price_normal_per_unit": 70.26,
    "price_normal_per_unit_int": "70",
    "price_normal_per_unit_frac": "26",
    "price_current": 61.83,
    "price_current_int": "61",
    "price_current_frac": "83",
    "price_current_per_unit": 61.83,
    "price_current_per_unit_int": "61",
    "price_current_per_unit_frac": "83",
    "price_30day_lowest": 59.52,
    "price_deposit": "1",
    "price_deposit_int": "00",
    "price_deposit_frac": "00",
    "discount_percent": "12",
    "price_unit_l1": "PARI",
    "price_unit_l2": "ST",
    "package_unit_size": 2,
    "package_unit_l1": "PR",
    "package_unit_l2": "PR",
    "product_features_1": "Waterproof",
    "product_features_2": "Lightweight",
    "product_features_3": "Reflective",
    "product_features_4": "Flexible sole",
    "product_features_5": "Breathable lining",
    "product_features_6": "Feature 10",
    "product_features_7": "",
    "product_features_8": "",
    "s2p_rt_additional_text": "Additional info 10",
    "target_market_text_l1": "Outdoor / School / Waterproof",
    "target_market_text_l2": "Outdoor / Skola",
    "marketing_text_l1": "Korkealaatuinen lasten kenkä Ruskea.",
    "marketing_text_l2": "Högkvalitativa barnskor Ruskea.",
    "ingredients_l1": "",
    "ingredients_l2": "",
    "origin_country_l1": "Finland",
    "origin_country_l2": "Finland",
    "attr_gluten_free": "",
    "attr_vegan": "0",
    "attr_lactose_low": "",
    "attr_lactose_free": "",
    "attr_organic": "0",
    "attr_alcohol_pct": "0",
    "attr_local": "0",
    "attr_quality_class": "A",
    "age_limit": "6+",
    "variable_weight_product": "1",
    "scale_number": "6",
    "blue_swan": "1",
    "top_brand": "ECCO",
    "consumer_info_l1": "Waterproof / Lightweight",
    "consumer_info_l2": "Vattentät / Lätt",
    "consumer_info_1_l1": "Waterproof",
    "consumer_info_2_l1": "Lightweight",
    "consumer_info_3_l1": "Reflective",
    "consumer_info_4_l1": "Flexible",
    "consumer_info_5_l1": "Durable",
    "consumer_info_6_l1": "Comfort fit",
    "consumer_info_7_l1": "",
    "consumer_info_8_l1": "",
    "consumer_info_1_l2": "Vattentät",
    "consumer_info_2_l2": "Lätt",
    "consumer_info_3_l2": "Reflex",
    "consumer_info_4_l2": "Flexibel",
    "consumer_info_5_l2": "Hållbar",
    "consumer_info_6_l2": "Bekväm",
    "consumer_info_7_l2": "",
    "consumer_info_8_l2": "",
    "assortment_start": "2026-08-10",
    "assortment_end": "2027-03-10",
    "assortment_status": "3",
    "product_group": "K",
    "aims_price_normal": 70.26,
    "aims_price_sale": 61.83,
    "aims_discount_pct": 12
  }
]



function getAvailableCategories() {
  return [...new Set(DUMMY_DS_ARTICLES.map((a) => a.CATEGORY))];
}

/**
 * Get a random article
 */
function getRandomArticle() {
  const index = Math.floor(Math.random() * DUMMY_DS_ARTICLES.length);
  return DUMMY_DS_ARTICLES[index];
}

// Export as CommonJS
module.exports = {
  DUMMY_DS_ARTICLES,
  getAvailableCategories,
  getRandomArticle
};
